kukhariev/ngx-uploadx

integrations/ng10/src/app/on-push/on-push.component.ts
src/uploadx/lib/error-handler.spec.ts
src/uploadx/lib/error-handler.ts
src/uploadx/lib/interfaces.ts
src/uploadx/lib/uploader.ts

BREAKING CHANGE: Rename RequestParams to RequestOptions
BREAKING CHANGE: Removed `*All` from UploadAction
BREAKING CHANGE: Strongly typed response body

interfaces refactoring

---

src/app/app.component.ts
src/app/digest.ts
src/app/on-push/on-push.component.ts
src/uploadx/lib/ajax.ts
src/uploadx/lib/interfaces.ts
src/uploadx/lib/tus.spec.ts
src/uploadx/lib/uploader.spec.ts
src/uploadx/lib/uploader.ts
src/uploadx/lib/uploaderx.spec.ts
src/uploadx/lib/uploaderx.ts
src/uploadx/lib/uploadx.service.spec.ts
src/uploadx/lib/uploadx.service.ts
src/uploadx/public-api.ts
uploader-examples/multipart-form-data.ts
uploader-examples/multipart-multer.ts

Allow using third-party packages for requests.
```ts
// Axios example: 
const instance = Axios.create({
/* put axios common config here */
});
class AxiosRequest implements Ajax {
request = (config: AjaxRequestConfig) => {
const cancelToken = new Axios.CancelToken(c => (config.canceler.onCancel = c));
return instance.request({ ...config, cancelToken });
};
}
const axiosRequestFactory = (): Ajax => new AxiosRequest();
@NgModule({
declarations: [
//  ...
],
imports: [
// ...
UploadxModule
],
providers: [{ provide: UPLOADX_AJAX, useFactory: axiosRequestFactory }],
bootstrap: [AppComponent],
exports: []
})
export class AppModule {}
```

feat: injectable ajax lib

---

src/uploadx/lib/uploadx.directive.ts
src/uploadx/lib/uploadx.service.ts

Fixes annoying build-time warning 
`WARNING: 'OnDestroy' and 'OnInit' are imported from external module '@angular/core' but never used`
https://github.com/ng-packagr/ng-packagr/issues/1543#issuecomment-593873874

build:  fix ng-packagr unused import warning

---

src/uploadx/lib/uploadx.directive.ts
src/uploadx/lib/uploadx.service.ts

Fixes annoying build-time warning 
`WARNING: 'OnDestroy' and 'OnInit' are imported from external module '@angular/core' but never used`
https://github.com/ng-packagr/ng-packagr/issues/1543#issuecomment-593873874

chore:  fix ng-packagr unused import warning

---

src/app/directive-way/directive-way.component.ts
src/uploadx/lib/retry-handler.spec.ts
src/uploadx/lib/retry-handler.ts
src/uploadx/lib/uploader.ts

Support `Retry-After: <delay-seconds>` format used in https://github.com/Chocobozzz/PeerTube/pull/4175

fix: support `Retry-After` header

---

src/uploadx/lib/interfaces.ts
src/uploadx/lib/uploader.ts

Add adaptive chunk size limit  to UploadxOptions.
Additional parameters are still available as `DynamicChunk` static properties.

fix: `maxChunkSize` option

---

README.md
src/app/tus/tus.component.ts
src/uploadx/lib/ajax.ts
src/uploadx/lib/retry-handler.ts
src/uploadx/lib/uploader.ts

Allow set  interval after which unfinished requests must be retried
```ts
options: UploadxOptions = {
endpoint: `${environment.api}/files?uploadType=tus`,
retryConfig: { timeout: 10_000 }
```
will probably closes  #310 by @siovene

fix: add timeout option

---

README.md
src/uploadx/lib/retry-handler.ts
src/uploadx/lib/uploader.ts

Prevents auto-DDoS for responses with missing or  invalid range/offset and also improves support for long post-upload operations with polling

fix: no range/offset retry delay option

---

src/app/directive-way/directive-way.component.ts
src/uploadx/lib/interfaces.ts
src/uploadx/lib/options.ts
src/uploadx/lib/store.ts
src/uploadx/lib/uploader.ts
src/uploadx/lib/uploadx.service.spec.ts
src/uploadx/lib/uploadx.service.ts
src/uploadx/public-api.ts

Added option `storeIncompleteHours`. The default value is 24 hours.
Resume URLs will now be automatically removed from localStorage when they expire.

fix: limit resumable upload lifetime

---

src/uploadx/lib/options.ts

Allow undoing #318 by setting `chunkSize` or `maxChunkSize` options.

fix: not apply iOS patch if chunk size is limited

---

README.md
src/app/directive-way/directive-way.component.ts
src/uploadx/lib/options.ts
src/uploadx/lib/uploadx.service.spec.ts
src/uploadx/lib/uploadx.service.ts

set `storeIncompleteHours` to 0 to disable storing resume URLs
BREAKING CHANGE: Removed deprecated `storeIncompleteUploadUrl` option.

refactor: remove `storeIncompleteUploadUrl` option

---

src/app/app.component.ts
src/uploadx/lib/dynamic-chunk.spec.ts
src/uploadx/lib/dynamic-chunk.ts
src/uploadx/lib/uploader.ts
src/uploadx/lib/utils.spec.ts
src/uploadx/lib/utils.ts

Changed the chunk time range from 2 - 8 sec to 8 - 24 sec.
This noticeably reduces server and client overhead and decreases upload time.

perf(dynamic-chunk): increase chunks time limits

---

src/app/app.module.ts
src/uploadx/lib/uploadx-drop.directive.spec.ts
src/uploadx/lib/uploadx-drop.directive.ts
src/uploadx/lib/uploadx.directive.ts

Directive should apply `multiple`, `allowedTypes` options from a module or service.

fix(directive): get options from service or module

---

src/app/auth.service.ts
src/app/directive-way/directive-way.component.ts

Fixed example of using the authorization service.
Authorization token is now also correctly updated on 401 error.

chore(app): auto-update auth token on 401 code

---

src/uploadx/lib/uploader.ts

For convenient usage, set initial progress to 0 to let the consumer to skip to check if progress isn't NaN.

fix: set initial progress to 0

---

src/uploadx/lib/interfaces.ts
src/uploadx/lib/uploader.spec.ts
src/uploadx/lib/uploader.ts

- now it is easier not to send authorization for some requests to external URLs without using the `Authorize` option
```ts
await this.request({
method: 'PUT',
body,
url: externalUrl,
skipAuthorization: true
})
```

refactor: added `skipAuthorization` request option

---

src/uploadx/lib/ajax.ts
src/uploadx/lib/interfaces.ts
src/uploadx/lib/uploader.ts

- replace `Canceler` with native `AbortSignal` to abort requests since `Canceler` does not support multiple event listeners and for better compatibility

refactor:  use `AbortSignal` for abort

---

src/app/tus/tus.component.html
src/app/tus/tus.component.ts
src/uploadx/lib/uploadx-drop.directive.ts

- When `multiple` option is set to `false`, dropping multiple files is not allowed.

fix(directive): drag & drop if `multiple` disabled

---

src/app/app.module.ts

- Remove the deprecated and incompatible with Angular 16 option `relativeLinkResolution`.

chore(app): remove `relativeLinkResolution`

---

src/uploadx/lib/uploadx.service.spec.ts
src/uploadx/lib/uploadx.service.ts

- Use `inject` function over the `constructor` for dependency injection

refactor: use inject() for di

---

angular.json
scripts/build-app.js

- To ensure the build process terminates properly, disable Angular CLI analytics.

chore: disable usage analytics

---

.github/actions/cached-npm-install/action.yml
.github/workflows/integration.yml
.github/workflows/playwright.yml
.github/workflows/publish.yml
.github/workflows/test.yml

- Upgrade Node.js 16 actions to Node.js 20 to avoid deprecation warning

ci: update actions to v4

---

README.md

- Correct syntax in usage example
Ref #452

docs: fix usage example typo

---

src/uploadx/lib/uploader.ts
uploader-examples/multipart-form-data.ts

Change `_authorize` and `_prereques` from private to protected to easily change the authorization type in the custom uploaders.

refactor: change `_authorize` and `_prereques` from private to protected

---

angular.json

- Use `buildTarget` instead of deprecated `browserTarget`.

chore: update workspace config
