src/uploadx/src/uploader.ts, src/uploadx/src/uploadx.service.ts
fixed: #30 Cancelled Uploads stays in upload queue of upload service
fixed: #29 Complete uploaded files cannot be removed
=> Fixed Issues #29 and #30

src/uploadx/src/uploadx.service.spec.ts, src/uploadx/src/uploadx.service.ts
Reduce the number of unnecessary changesDetect calls
=> perf:  ngzone bypass

src/uploadx/src/interfaces.ts, src/uploadx/src/uploader.ts, src/uploadx/src/uploadx.directive.spec.ts, src/uploadx/src/uploadx.service.spec.ts, src/uploadx/src/uploadx.service.ts, src/uploadx/src/utils.ts
BREAKING CHANGE:  changed `UploadxControlEvent` interface
=> refactor:  uploads control

src/uploadx/lib/uploader.ts
=> fix: missing errors logging

README.md, integrations/ng10/src/app/directive-way/directive-way.component.ts, integrations/ng10/src/app/on-push/on-push.component.ts, integrations/ng10/src/app/service-code-way/service-code-way.component.ts, integrations/ng10/src/app/service-code-way/uploader-ext.class.ts, integrations/ng8/src/app/directive-way/directive-way.component.ts, integrations/ng8/src/app/on-push/on-push.component.ts, integrations/ng8/src/app/service-code-way/service-code-way.component.ts, integrations/ng8/src/app/service-code-way/uploader-ext.class.ts, src/app/directive-way/directive-way.component.ts, src/app/multi-service/multi-service.component.spec.ts, src/app/on-push/on-push.component.ts, src/app/service-code-way/service-code-way.component.ts, src/app/service-code-way/uploader-ext.class.ts, src/uploadx/lib/interfaces.ts, src/uploadx/lib/store.ts, src/uploadx/lib/uploader.spec.ts, src/uploadx/lib/uploader.ts, src/uploadx/lib/uploadx.service.ts, src/uploadx/lib/utils.ts
Function called before every request.
see 'on-push' component  example
=> feat: prerequest option

package.json
BREAKING CHANGE: Dropped support for Anglular <7.x
=> build: update peerDependencies

src/uploadx/lib/uploader.ts
Following issue is related: https://github.com/kukhariev/ngx-uploadx/issues/252
=> refactor: 💡 Free the getResponseBody

src/uploadx/lib/uploader.ts
=> Metadata fixes

README.md, src/app/auth.service.ts, src/app/on-push/on-push.component.ts, src/app/tus/tus.component.ts, src/uploadx/lib/interfaces.ts, src/uploadx/lib/options.ts, src/uploadx/lib/uploader.ts, src/uploadx/lib/uploadx.service.spec.ts, src/uploadx/lib/uploadx.service.ts
Function used to apply authorization token
BREAKING CHANGE: removed obsolete 'setAuth()' method
=> feat: authorize option

src/uploadx/lib/retry-handler.spec.ts, src/uploadx/lib/retry-handler.ts
Allows you to specify your own function that determines whether to retry the request.
#297
=> feat: shouldRetry function

src/uploadx/lib/retry-handler.spec.ts, src/uploadx/lib/retry-handler.ts, src/uploadx/lib/uploader.ts
=> fix: infinite retries at error-success loop

src/uploadx/lib/store.ts
=> fix: more reliable testing of localstorage access

src/uploadx/lib/options.ts, src/uploadx/lib/uploadx.service.ts, src/uploadx/lib/utils.ts
=> fix: disable chunks on iOS

package.json, server/index.js, src/uploadx/lib/tus.ts, src/uploadx/lib/uploaderx.ts
better tus servers compatibility
=> refactor: getting offset from response

src/uploadx/lib/utils.spec.ts, src/uploadx/lib/utils.ts
=> fix(tus): support metadata empty values

package.json, src/app/file-generator/download/download.component.spec.ts, src/app/multi-service/a/a.component.spec.ts, src/app/multi-service/b/b.component.spec.ts, src/app/multi-service/multi-service.component.spec.ts, src/app/multiple-directive/multiple-directive.component.spec.ts, src/app/on-push/on-push.component.spec.ts, src/app/service-code-way/service-code-way.component.spec.ts
=> style: prettier update

src/app/auth.service.ts, src/app/directive-way/directive-way.component.ts, src/uploadx/lib/uploader.ts
Added support for error handling of auth token functions.
=> refactor: auth token update

commitlint.config.js, package.json
- update commitlint dependency to v16.3.0
- move commitlint config to package.json
=> chore: update commitlint dependency to v16.3.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
- enhance github issue templates for bug, questions and feature request
=> chore: update issue templates

integrations/package.json
- add missing `serve` command for angular@next build
=> test(integration): add serve for angular@next build

.github/ISSUE_TEMPLATE/config.yml, README.md
- add issues and contributing notes
- add node-uploadx issue link
- remove unnecessary links
=> docs: add issues and contributing notes

.github/workflows/integration.yml, package.json
- The `ngx-uploadx` supports Angular v14.x.x.
Fixes #
=> feat: support angular v14

src/app/digest.ts, src/app/on-push/on-push.component.ts, src/app/service-way/service-way.component.ts, src/uploadx/lib/uploader.ts
- allows to implement parallel uploading of chunks
- can be used when calculating the file checksum in the background 
Fixes #
=> feat: add `getChunk` parameters

.eslintrc.json, src/app/auth.service.ts, src/app/digest.ts, src/app/directive-way/directive-way.component.spec.ts, src/app/service-way/service-way.component.ts, src/uploadx/lib/ajax.spec.ts, src/uploadx/lib/ajax.ts, src/uploadx/lib/canceler.ts, src/uploadx/lib/dynamic-chunk.spec.ts, src/uploadx/lib/interfaces.ts, src/uploadx/lib/options.ts, src/uploadx/lib/retry-handler.spec.ts, src/uploadx/lib/store.spec.ts, src/uploadx/lib/tus.spec.ts, src/uploadx/lib/uploader.ts, src/uploadx/lib/uploaderx.spec.ts, src/uploadx/lib/uploadx-drop.directive.ts, src/uploadx/lib/uploadx.service.spec.ts, src/uploadx/lib/uploadx.service.ts, src/uploadx/lib/utils.ts
- `axios` compatible headers type
-  fixing a bunch of miscellaneous type errors
=> style(lint): stricter eslint rules

.github/workflows/browserstack.yml, .github/workflows/integration.yml
=> ci: update workflow schedules

README.md, src/uploadx/lib/retry-handler.ts, src/uploadx/lib/uploader.ts
- an option to determine whether to keep/discard partial chunks:
```ts
options: UploadxOptions = {
retryConfig: {
keepPartial: statusCode => statusCode >= 400 // default
}
};
```
```ts
options: UploadxOptions = {
chunkSize: 0, // no chunking
retryConfig: {
keepPartial: true // will keep already uploaded data on network errors
}
};
```
=> feat: option to keep partial chunks

.github/actions/cached-npm-install/action.yml, .github/workflows/browserstack.yml, .github/workflows/integration.yml, .github/workflows/publish.yml, .github/workflows/test.yml
- Caching dependencies to speed up workflows
=> ci: use npm cache

server/index.js
- restore debug log after `@uploadx/core` upgrade
=> chore(server): use logLevel

src/uploadx/lib/uploader.ts
- Auto-delete key/value pair with .url key from store
=> refactor: add .url to the auto-delete store key

src/app/directive-way/directive-way.component.html, src/app/directive-way/directive-way.component.ts, src/app/on-push/on-push.component.html, src/app/on-push/on-push.component.ts, src/uploadx/lib/interfaces.ts, src/uploadx/lib/uploader.ts, src/uploadx/lib/uploaderx.spec.ts, src/uploadx/lib/uploaderx.ts
- added  uploader `.update(data)` method (PATCH request with JSON body)
- added new option to update metadata during or after uploading
```ts
this.uploadService.control({ action: 'update', metadata: { filename: newFilename } });
```
=> feat: add `update` method and event

src/app/service-code-way/service-code-way.component.ts, src/environments/environment.prod.ts
- move demo server to https://uploadx-demo-server.onrender.com
=> chore:  update demo server url

scripts/build-app.js
- fix legacy `migrateOnly` angular cli flag
- fix `ng update` cwd
#
=> test: fix ng migration commandline

package.json, scripts/build-app.js
- compatibility fixes for some versions of Angular CLI
=> test(integration): update build script

src/uploadx/lib/ajax.ts
- If uploader `responseType` set to `json`, non-json bodies are discarded. This PR is to fix this issue.
=> fix(ajax): non-json response bodies are discarded

src/uploadx/lib/ajax.ts
- `responseType` handling improvements
=> refactor(ajax): `responseType` handling improvements

src/app/auth.service.ts, src/uploadx/lib/uploader.ts
- send status сhange at the very beginning of the upload
=> fix: skipped first `uploading` event

src/uploadx/lib/uploadx-drop.directive.ts
- fix drag type detection
- apply custom style on dragover
=> fix: apply custom style on dragover

src/app/app.component.html, src/app/app.component.ts, src/app/directive-way/directive-way.component.html, src/app/multi-service/a/a.component.html, src/app/multi-service/b/b.component.html, src/app/multiple-directive/multiple-directive.component.html, src/app/on-push/on-push.component.html, src/app/service-code-way/service-code-way.component.html, src/app/service-way/service-way.component.html, src/app/tus/tus.component.html, src/styles.scss
=> chore: app layout refactoring

src/uploadx/lib/uploadx-drop.directive.spec.ts, src/uploadx/lib/uploadx.directive.spec.ts, src/uploadx/lib/uploadx.service.spec.ts
- add missing drag & drop with options test
=> test: add missing drag & drop with options test

angular.json, package.json, src/uploadx/lib/utils.ts
- Simplify iOS detection code.
- Include a script to ease testing on mobile devices.
=> refactor: ios detection

.eslintrc.json, server/index.js
- Use environment variables to configure server
=> chore: use env variables to configure server

src/uploadx/lib/uploadx-drop.directive.ts, src/uploadx/lib/uploadx.directive.ts
- Ignore dropped directories as a workaround
Fixes #422
=> fix: ignore dropped folders

package.json
=> fix: support angular v16

src/app/app.module.ts, src/app/config.ts, src/app/directive-way/directive-way.component.ts, src/app/multi-service/a/a.component.ts, src/app/multi-service/b/b.component.ts, src/app/multiple-directive/multiple-directive.component.ts, src/app/on-push/on-push.component.ts, src/app/service-code-way/service-code-way.component.ts, src/app/service-way/service-way.component.ts, src/app/tus/tus.component.ts, src/environments/environment.prod.ts, src/environments/environment.ts
-  remove the server URL from the Angular environment
=> chore(app): server url config

src/uploadx/lib/options.ts, src/uploadx/lib/uploadx.service.ts, src/uploadx/lib/utils.spec.ts, src/uploadx/lib/utils.ts
=> fix: disable options patch on ios 15.3+

scripts/build-app.js, src/app/app.component.html, src/styles.scss
=> chore(app): gh icon fix

src/app/app.component.html, src/app/app.routes.ts, src/app/directive-way/directive-way.component.spec.ts, src/app/multiple-directive/multiple-directive.component.spec.ts, src/app/standalone/standalone.component.html, src/app/standalone/standalone.component.spec.ts, src/app/standalone/standalone.component.ts, src/uploadx/lib/uploadx-drop.directive.spec.ts, src/uploadx/lib/uploadx-drop.directive.ts, src/uploadx/lib/uploadx.directive.spec.ts, src/uploadx/lib/uploadx.directive.ts, src/uploadx/lib/uploadx.module.ts
- migrate directives to standalone
=> feat: standalone directives

src/uploadx/lib/uploadx.provider.ts, src/uploadx/public-api.ts
- added provider function for use in a standalone app
=> feat: provider to configure

karma.conf.js, src/app/directive-way/directive-way.component.spec.ts, src/app/on-push/on-push.component.spec.ts, src/app/service-code-way/service-code-way.component.spec.ts, src/app/service-way/service-way.component.spec.ts, src/app/service-way/service-way.component.ts, src/app/standalone/standalone.component.spec.ts, src/app/tus/tus.component.spec.ts, src/uploadx/lib/ajax.spec.ts, src/uploadx/lib/dynamic-chunk.spec.ts, src/uploadx/lib/retry-handler.spec.ts, src/uploadx/lib/tus.spec.ts, src/uploadx/lib/uploader.spec.ts, src/uploadx/lib/uploaderx.spec.ts, src/uploadx/lib/uploadx.directive.spec.ts, src/uploadx/lib/uploadx.service.spec.ts, src/uploadx/lib/utils.spec.ts
- remove useless app tests
- various unit test fixes
=> test: various fixes

src/uploadx/lib/uploader.spec.ts, src/uploadx/lib/uploader.ts
- fix potential 1-second wait before the upload begins on some upload servers
=> fix: remove upload delay

src/uploadx/lib/retry-handler.ts, src/uploadx/lib/utils.ts
-  use `localCompare` to compare OS versions strings
=> refactor: compare os versions function

scripts/build-app.js
- force bilding  of a non-standalone test application
=> test(app): fix building angular 17 app

integrations/package.json, package.json
=> feat: support angular v17

.github/actions/cached-npm-install/action.yml, package.json
- Update required node engine to version 18.19.1 to align with Angular-cli v18.
=> build: update to node.js v18

scripts/build-app.js
- use 'npx ng' instead of 'ng' to ensure the correct version Angular CLI is used.
=> test(app): fix build script

package.json
- Fixed warning about Angular v18 during package installation.
=> fix: support angular v18

.husky/commit-msg, .husky/pre-commit, package.json
=> chore: husky deprecation fix

.github/actions/cached-npm-install/action.yml, tsconfig.json
=>  ci: npm cache fix

src/styles.scss
- fix sass global built-in functions deprecation warnings
=> refactor(app): prevent sass deprecation warnings

.github/workflows/integration.yml, package.json
- Update peer dependency range for @angular/core to 17.0.0 - 19.0.0
=> fix: support Angular v19

src/uploadx/lib/store.ts
- More reliable deletion of broken records
=> refactor: deleting expired records

src/styles.scss
=> chore(app): small style tweaks

LICENSE, src/uploadx/tsconfig.lib.json, uploader-examples/blob-uploader .ts
- add Azure Blob Storage uploader example
=> docs: add azure blob uploader example

package.json
- [fix npm audit](https://github.com/kukhariev/node-uploadx/pull/683)
=> chore: update @uploadx/core to v6.1.7
